export const customersData = [
  {
    id: "0",
    customerNumber: "HSD_JED_00205",
    customerName: "Shabab Trading Center",
    address: "Saudi Arabia, jeddha, anar towers",
    mobile: "9865324578",
  },
  {
    id: "1",
    customerNumber: "HSD_JED_00658",
    customerName: "4J Company Limited",
    address: "SAU",
    mobile: "9856254123",
  },
  {
    id: "2",
    customerNumber: "HSD_JED_00857",
    customerName: "Amir Al Bound EST",
    address: "Saudi Arabia, Malik station",
    mobile: "9845156525",
  },
  {
    id: "3",
    customerNumber: "HSD_JED_00578",
    customerName: "A&B Shakar Co Ltd",
    address: "Saudi Arabia, Tamlik towers",
    mobile: "8574961452",
  },
  {
    id: "4",
    customerNumber: "HSD_JED_01056",
    customerName: "AATCO Food Industries LLC",
    address: "Saudi Arabia, Miraj road",
    mobile: "98562457812",
  },
  {
    id: "5",
    customerNumber: "HSD_JED_08574",
    customerName: "Abbas Foood Factory",
    address: "Girhaik road, mumaj corner",
    mobile: "9874582146",
  },
  {
    id: "6",
    customerNumber: "HSD_JED_07832",
    customerName: "Abdel Hati Abdelha & Sons",
    address: "Saudi Arabia, Mumtaj road",
    mobile: "9852167535",
  },
  {
    id: "7",
    customerNumber: "HSD_JED_03254",
    customerName: "Abdul Alarni EST",
    address: "Saudi Arabia, Navab junction",
    mobile: "9825417696",
  },
  {
    id: "8",
    customerNumber: "HSD_JED_01026",
    customerName: "Abdul Hadi Bafarat EST",
    address: "Saudi Arabia, Zizami est colony",
    mobile: "9878451265",
  },
  {
    id: "9",
    customerNumber: "HSD_JED_07852",
    customerName: "Abdul Jameel Rafik Retail Co.",
    address: "Saudi Arabia, Navaj road",
    mobile: "9877254163",
  },
];
