export const servicemenData = [
  {
    id: "0",
    name: "Aziz Hasan",
    shortName: "Aziz",
    businessType: "Audit",
    mobile: "9832457812",
  },
  {
    id: "1",
    name: "Husain Shaikh",
    shortName: "Husain",
    businessType: "Audit",
    mobile: "9856324512",
  },
  {
    id: "2",
    name: "Sharif Akhtar",
    shortName: "Sharif",
    businessType: "Maintenance",
    mobile: "9854172635",
  },
  {
    id: "3",
    name: "Varun Mishra",
    shortName: "Varun",
    businessType: "Maintenance",
    mobile: "9852417631",
  },
  {
    id: "4",
    name: "Sunil Sharma",
    shortName: "Sunil",
    businessType: "Audit",
    mobile: "9874547852",
  },
  {
    id: "5",
    name: "Navaj shaikh",
    shortName: "Navaj",
    businessType: "Refill",
    mobile: "9852416378",
  },
  {
    id: "6",
    name: "Shivam Kumar",
    shortName: "Shivam",
    businessType: "Refill",
    mobile: "9885962541",
  },
  {
    id: "7",
    name: "Arjun Rampal",
    shortName: "Arjun",
    businessType: "Audit",
    mobile: "9865457812",
  },
  {
    id: "8",
    name: "Subhramnian Yadav",
    shortName: "Shubhramanian",
    businessType: "Maintenance",
    mobile: "9841526378",
  },
  {
    id: "9",
    name: "Shrinivas Kumar",
    shortName: "Shri",
    businessType: "Refill",
    mobile: "8549624151",
  },
];
